version: "3.8"

networks:
  goat:
    driver: bridge

services:
  jenkins_server:
    platform: "linux/amd64"
    image: cidersecurity/goat-jenkins-server:latest
    networks:
      - goat
    container_name: jenkins-server
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
  jenkins_agent:
    image: cidersecurity/goat-jenkins-agent:latest
    container_name: jenkins-agent
    networks:
      - goat
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC33zkdtvwp8giZLp1mVUbqzCKi0KIiWD8/towT0+9k1SCDYjJ/YVPqKidkSefYaKBgJ1yFcWa9qroXAUd5nACXN3Xdes2fe4w+xZ8GQTpqHKyStEHy6R9QXi00r/VxGcmBYZWLifEyzV//PiRC+hUaG27JeeBnkZ1FEOyXUunpaPixNaDkfnLbCimflkd2uYH2arMY+FdOH950ezow/+v4vsNrzoMwVVCCSg/dIJBS2G/JaoAbbQgIGo63Kyz0j++rIInsXMFmxhy9hEpViX/tEorFzGh4gUvJPLy3IDjWjUz/Nfte9By6usQjN/1plJcuP+rUqrjjGeMpfhDP6aq5ZvfuPTmXOVkWJ9vJZaK2BCtSZk1vOJR4luxCyUZQbKgb3jS9YZ4N1ZS26z3EKwJGP/acNtEMx2u2zhY7zXdG7ca1Qo1yeVDMRctlvH++KMEYX/ZR6LqYlJyV6TFICZVUT7dLF65gq68UyIFswMu9pQ8/VvIMkkO6eiU1cqFr8gc=
  gitea:
    image: cidersecurity/goat-gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - goat
    ports:
      - "3000:3000"
  ctfd:
    image: cidersecurity/goat-ctfd:latest
    container_name: ctfd
    ports:
      - "8000:8000"
    networks:
      - goat
  localstack:
    container_name: localstack
    image: localstack/localstack:0.14.1-amd64
    networks:
      - goat
  lighttpd:
    image: cidersecurity/goat-lighttpd:latest
    container_name: lighttpd
    networks:
      - goat
    ports:
      - "8008:80"
      - "2222:22"
